### PR TITLE
fix(auth-cookies): fix #1287 rewrite cookie set remove service

### LINKED ISSUE #1287: [AUTH] logout
logout problem with cookies and subroute cookies

### PR DESCRIPTION
**Pull request by kwiss**
unnamed

### CODE REVIEW

File: packages/app/src/piwik.js [hunk 1]
```diff
@@ -28,7 +27,7 @@ export const untrackUser = () => {
 };
 
 function getJWTPayloadFormLocalStorageIdToken() {
-  const token = storageService.getToken() || "";
+  const token = cookie.get("token");
   const [, payloadPart = ""] = token.split(".");
```
Comment (gershon) [inline packages/app/src/piwik.js]:
```
TypeError: Cannot read property 'split' of undefined
getJWTPayloadFormLocalStorageIdToken
./src/piwik.js:29
```
